version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs: 
  test-deploy:
    executor: python/default
    steps:
      - python/dist
      - run:
          command: | 
            twine upload --repository testpypi dist/*
  
  orbTest:
    executor: python/default
      # tag: << parameters.tag >>
    steps: 
      - python/install-packages:
          args: pytest
      - run:
          command: |
            pipenv run pytest --version
          name: Test it
  
  toxTest:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: ./dockertest.sh


workflows:
  version: 2
  test-deploy:
    jobs:
      - toxTest:
          filters:
            branches:
              only: release

      - test-deploy:
          requires:
            - toxTest
          filters:
            branches:
              only: release
  tests:
    jobs:
      # - orbTest
      - toxTest
      - orbTest:
          matrix:
            parameters:
              tag: ["3.6", "3.7", "3.8", "3.9"]

  
