version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs: 
  deploy:
    executor: python/default
    steps:
      - python/dist

  orbTest:
    executor: python/default
    steps: 
      - python/install-packages:
          args: pytest
      - run:
          command: |
            pipenv run pytest --version
          name: Test it
  
  toxTest:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: ./dockertest.sh

workflows:
  version: 2
  deploy:
    jobs:
      - toxTest:
          filters:
            branches:
              only: release

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: release
  tests:
    jobs:
      - orbTest
      - toxTest

  
