version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs: 
  test-deploy:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run:
          command: | 
            twine upload --repository testpypi dist/*
  
  # Test multiple python version by running multiple jobs
  orbTest:
    parameters:
      tag:
        description: "python version"
        default: "3.8"
        type: string
    executor:
      name: python/default
      tag: <<parameters.tag>>
    steps: 
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pypi-cache: false
          args: -r test_requirements.txt
      - run:
          command: |
            pytest
          name: Test it
  
  # Test multiple python version by running a single job with tox
  toxTest:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: ./dockertest.sh


workflows:
  version: 2
  test-deploy:
    jobs:
      - toxTest:
          filters:
            branches:
              only: test-release

      - test-deploy:
          requires:
            - toxTest
          filters:
            branches:
              only: test-release
  tests:
    jobs:
      - toxTest
      - orbTest:
          matrix:
            parameters:
              tag: ["3.6", "3.7", "3.8", "3.9"]

  
